# ______
# |  ____|
# | |__   _ ____   _____  _   _ ___
# |  __| | '_ \ \ / / _ \| | | / __|
# | |____| | | \ V / (_) | |_| \__ \
# |______|_| |_|\_/ \___/ \__, |___/
#                          __/ |
#                         |___/     By PetteriM1
#
# Warning: Editing this file incorrectly will make the plugin not to load

name: Envoys
main: me.petterim1.envoys.Envoys
version: "${pom.version}"
api: ["1.0.9"]
author: PetteriM1
description: Envoys plugin for Nukkit
website: https://nukkitx.com/resources/envoys.358/

permissions:
  envoys.command.main:
    description: "Permission for /envoys command and all its sub-commands if not overwritten by other permissions"
    default: true
  envoys.command.time:
    description: "Permission for /envoys time command"
    default: true
  envoys.command.start:
    description: "Permission for /envoys start command"
    default: op
  envoys.command.stop:
    description: "Permission for /envoys stop command"
    default: op
  envoys.command.drops:
    description: "Permission for /envoys drops command"
    default: op
  envoys.command.edit:
    description: "Permission for /envoys edit command"
    default: op
  envoys.command.left:
    description: "Permission for /envoys left command"
    default: op
